name: CI example 
on: 
  push:
        branches: main
jobs:
  docker-build-push-project:
    name: Docker Build and Push Project
    runs-on: ubuntu-latest
    needs: release-project
    steps:
      - name: Download Application Artifact
        uses: actions/download-artifact@v2
        with:
          name: node-rest-api
      - name: View content
        run: ls -R
      - name: Unzip artifact
        uses: actions/extract@v2
        with:
          archive-file: node-rest-api.zip
          destination: extracted-release
      - name: View content
        run: ls -R
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
  release-project:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
    - name: Download Application Artifact
      uses: actions/download-artifact@v2
      with:
        name: node-rest-api
    - name: View content
      run: ls -R
    - name: Create GitHub release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./node-rest-api.zip
        asset_name: node-rest-api-v${{ github.run_number }}.zip
        asset_content_type: application/zip
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - run: node --version
        name: Check Node Version
      - run: npm --version
        name: Check NPM Version
      - uses: actions/checkout@v2
        name: Checkout Repository
      - run: npm install
        name: Install Dependencies
      - run: npm test
        name: Run Tests
      - name: Archive Project Artifacts in Zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'node-rest-api.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Upload application pacakge
        uses: actions/upload-artifact@v2
        with:
          name: node-rest-api
          path: ./node-rest-api.zip