name: CI example
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
        name: Check Node Version
      - run: npm --version
        name: Check NPM Version
      - uses: actions/checkout@v2
        name: Checkout Repository
      - run: npm install
        name: Install Dependencies
      - run: npm test
        name: Run Tests
      - name: Archive Project Artifacts in Zip
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'node-rest-api.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Upload application pacakge
        uses: actions/upload-artifact@v2
        with:
          name: node-rest-api
          path: ./node-rest-api.zip